# Generated by Django 5.2.4 on 2025-07-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('year', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cor')),
                ('mileage', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Quilometragem')),
                ('price', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Valor Veiculo')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling', models.DateTimeField(verbose_name='Data')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('custome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Cliente')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Teste Drive',
                'verbose_name_plural': 'Teste Drives',
            },
        ),
    ]
