# Generated by Django 5.2.4 on 2025-07-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdrive',
            old_name='custome',
            new_name='customer',
        ),
    ]
