# Generated by Django 5.2.4 on 2025-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_custome_testdrive_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Disponivel'),
        ),
    ]
