# Generated by Django 5.2.4 on 2025-07-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='AGUARDANDO', verbose_name='Status da Proposta')),
                ('value', models.IntegerField(verbose_name='Valor Final')),
                ('date_proposal', models.DateTimeField(verbose_name='Data da Prosposta')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Cliente')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Vend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateTimeField(verbose_name='Data da Venda')),
                ('payment', models.CharField(choices=[('PIX', 'Pix'), ('DEBITO', 'Debito'), ('CREDITO', 'Credito')], default='CREDITO', verbose_name='Metodo Pagamento')),
                ('value', models.IntegerField(verbose_name='Valor Final')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Cliente')),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.saller', verbose_name='Vendedor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
