# Generated by Django 5.2.4 on 2025-07-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesproposal',
            options={'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
    ]
