# Generated by Django 5.2.4 on 2025-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesproposal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproposal',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final'),
        ),
        migrations.AlterField(
            model_name='vend',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final'),
        ),
    ]
